PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sdo: <https://schema.org/>
PREFIX sys: <https://localhost:5000/>


INSERT {
    GRAPH <https://inferred.com> {
        ?r a dcat:Resource ;
           dcat:distribution  sys: , sys:sparql , ?cr .

        ?cr dcterms:title ?cr_title .

        ?c dcterms:hasPart ?r .
    }
}
WHERE {
    GRAPH ?g {
        VALUES ?dcat_type { dcat:Resource dcat:Dataset }
        ?r a ?dcat_type .

        ?c a dcat:Catalog .

        OPTIONAL {
            ?r sdo:codeRepository ?cr .
        }

        OPTIONAL {
            ?r sdo:codeRepository/dcterms:title ?cr_title .
        }
    }
}