PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>


INSERT {
    GRAPH <https://inferred.com> {
  	    ?r dcat:distribution ?d .
        ?d a dcat:Distribution .
    }
}
WHERE {
    GRAPH ?g {
	    ?r dcat:distribution ?d
	}
}
