# Class each DataService as a Distribution

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>


INSERT {
    GRAPH <urn:local:inferred> {
        ?d a dcat:Distribution .
    }
}
WHERE {
    GRAPH ?g {
        VALUES ?dist_type { dcat:Distribution dcat:DataService }
        ?d a ?dist_type
    }
}
