# Title each Distribution from the Resource if it doesn't have a title

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>

INSERT {
    GRAPH <urn:local:inferred> {
  	    ?r dcat:distribution ?d .
        ?d dcterms:title ?t_new .
    }
}
WHERE {
    GRAPH ?g {
        ?r dcat:distribution ?d ;
            dcterms:title ?r_title .

        OPTIONAL {
          ?d dcterms:title ?t .
        }

        BIND (COALESCE (?t, CONCAT("Distribution for ", ?r_title)) AS ?t_new)
    }
}